apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
  labels:
    app: mern-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
        - name: mern-backend
          image: us-central1-docker.pkg.dev/social-media-mern-app-cloud/mern-backend-repo/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5000"
            - name: CONNECTION_URL
              value: "mongodb+srv://bhavyakc08:project14@cluster0.x9pre.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
            - name: JWT_SECRET
              value: "group14"

          # Adjusted Startup Probe
          startupProbe:
            httpGet:
              path: /health   # Change to a dedicated health check route
              port: 5000
            initialDelaySeconds: 40  # Increased to allow DB connection
            failureThreshold: 10  # Allows more retries before failure
            periodSeconds: 10
            timeoutSeconds: 5

          # Adjusted Liveness Probe
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 50  # Increased to avoid premature failure
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 5

          # Adjusted Readiness Probe
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 5

          # Added Resource Limits
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
