# Using Node.js LTS version
FROM node:16

# Setting working directory
WORKDIR /app

# Copying package.json and package-lock.json
COPY package*.json ./

# Installing only production dependencies
RUN npm install --omit=dev

# Copying the rest of the app
COPY . .

# Exposing the port
EXPOSE 5000

# Setting environment variable
ENV NODE_ENV=production

# Starting the server without nodemon
CMD ["node", "index.js"]
