# Using Node.js LTS version
FROM node:16

# Setting working directory
WORKDIR /app

# Copying package.json and package-lock.json
COPY package*.json ./

# Installing all dependencies (including dev dependencies)
RUN npm install

# Copying the rest of the app
COPY . .

# Exposing the port
EXPOSE 5000

# Using nodemon for live-reloading during development
CMD ["npx", "nodemon", "index.js"]
