# Use Node.js LTS version
FROM node:16

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install all dependencies (including dev dependencies)
RUN npm install

# Copy the rest of the app
COPY . .

# Expose the port
EXPOSE 5000

# Use nodemon for live-reloading during development
CMD ["npx", "nodemon", "index.js"]
