# Using Node.js LTS version
FROM node:16

# Setting working directory
WORKDIR /app

# Copying package.json and package-lock.json
COPY package*.json ./

# Installing only production dependencies
RUN npm install --omit=dev

# Copying the rest of the app
COPY . .

# Exposing the port
EXPOSE 5000

# Setting environment variables
ENV NODE_ENV=production \
    PORT=5000 \
    CONNECTION_URL='mongodb+srv://bhavyakc08:project14@cluster0.x9pre.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0' \
    JWT_SECRET='group14'

# Starting the server without nodemon
CMD ["node", "index.js"]