# web-service-loadbalancer.yaml
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: social-media-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer