apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  connection-url: "bW9uZ29kYitzcnY6Ly9iaGF2eWFrYzA4OnByb2plY3QxNEBjbHVzdGVyMC54OXByZS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA="

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  jwt-secret: "Z3JvdXAxNA=="