apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: social-media-app
    tier: web
spec:
  selector:
    app: social-media-app
    tier: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000