apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: social-media-app
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social-media-app
      tier: web
  template:
    metadata:
      labels:
        app: social-media-app
        tier: web
    spec:
      containers:
      - name: web-app
        image: gcr.io/social-media-backend-453104/social-media-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: connection-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool