apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 1  # Only one pod
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: gcr.io/social-media-mern-app-cloud/nodejs-app:latest  # Replace with your actual image
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "5000"
        - name: CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: connection-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /posts
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /posts
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  connection-url: bW9uZ29kYitzcnY6Ly9iaGF2eWFrYzA4OnByb2plY3QxNEBjbHVzdGVyMC54OXByZS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=  # Base64 encoded
  jwt-secret: Z3JvdXAxNA==  # Base64 encoded