name: Deploy Backend to GKE 

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: social-media-mern-app-cloud
  GKE_CLUSTER: mern-cluster
  GKE_ZONE: us-central1-a
  BACKEND_IMAGE: us-central1-docker.pkg.dev/social-media-mern-app-cloud/mern-backend-repo/backend

jobs:
  deploy:
    name: Deploy Backend to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Get GKE Credentials  # <-- ADD THIS STEP BEFORE KUBECTL COMMANDS
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

      - name: Deploy Backend to GKE
        run: kubectl apply -f k8s/backend-deployment.yaml

      - name: Deploy Load Balancer
        run: kubectl apply -f k8s/backend-loadbalancer.yaml
