name: Deploy Backend to GKE
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: social-media-mern-app-cloud
  GKE_CLUSTER: mern-cluster
  GKE_ZONE: us-central1-a
  BACKEND_IMAGE: us-central1-docker.pkg.dev/social-media-mern-app-cloud/mern-backend-repo/backend

jobs:
  deploy:
    name: Deploy Backend to GKE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'gke-gcloud-auth-plugin'
      
      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      
      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID
      
      - name: Clean up existing deployments
        run: |
          kubectl delete deployment mern-backend --ignore-not-found=true
          kubectl delete service backend-loadbalancer --ignore-not-found=true
          kubectl delete service backend-service --ignore-not-found=true
      
      - name: Deploy Backend to GKE
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          sleep 10
      
      - name: Deploy Services
        run: |
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/backend-loadbalancer.yaml
      
      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get services