name: Deploy to GKE
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: social-media-mern-app-cloud
  GKE_CLUSTER: mern-cluster
  GKE_ZONE: us-central1-a
  BACKEND_IMAGE: us-central1-docker.pkg.dev/social-media-mern-app-cloud/mern-backend-repo/backend
  FRONTEND_IMAGE: us-central1-docker.pkg.dev/social-media-mern-app-cloud/mern-frontend-repo/frontend

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'gke-gcloud-auth-plugin'
      
      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      
      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID
      
      - name: Cleanup Previous Deployment ( Frontend )
        run: |
         
          
          # Clean up frontend resources
          kubectl delete deployment mern-frontend --ignore-not-found=true
          kubectl delete service frontend-service --ignore-not-found=true
          
          echo "Previous frontend deployments cleaned up"

      - name: Build Backend
        run: |
          cd server
          docker build -t $BACKEND_IMAGE -f Dockerfile.prod .
          docker push $BACKEND_IMAGE

      - name: Build Frontend
        run: |
          cd client
          docker build -t $FRONTEND_IMAGE -f Dockerfile.prod .
          docker push $FRONTEND_IMAGE
      
      - name: Deploy Backend
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/backend-loadbalancer.yaml
          echo "Backend deployed successfully"

      - name: Deploy Frontend
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          echo "Frontend deployed successfully"
      
      - name: Verify Deployment
        run: |
          echo "Waiting for pods to be ready..."
          sleep 30
          echo "Current Pods:"
          kubectl get pods
          echo "Current Services:"
          kubectl get services