name: Deploy to GKE
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: social-media-mern-app-cloud
  GKE_CLUSTER: mern-cluster
  GKE_ZONE: us-central1-a
  BACKEND_IMAGE: us-central1-docker.pkg.dev/social-media-mern-app-cloud/mern-backend-repo/backend
  FRONTEND_IMAGE: us-central1-docker.pkg.dev/social-media-mern-app-cloud/mern-frontend-repo/frontend
  SHA: ${{ github.sha }}

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'gke-gcloud-auth-plugin'
      
      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      
      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

      - name: Build Backend
        run: |
          cd server
          docker build -t $BACKEND_IMAGE:$SHA -f Dockerfile.prod .
          docker push $BACKEND_IMAGE:$SHA

      - name: Build Frontend
        run: |
          cd client
          docker build -t $FRONTEND_IMAGE:$SHA -f Dockerfile.prod .
          docker push $FRONTEND_IMAGE:$SHA
      
      - name: Update Kubernetes Configs
        run: |
          # Replace image tags in deployment files
          sed -i "s|$BACKEND_IMAGE:latest|$BACKEND_IMAGE:$SHA|" k8s/backend-deployment.yaml
          sed -i "s|$FRONTEND_IMAGE:latest|$FRONTEND_IMAGE:$SHA|" k8s/frontend-deployment.yaml
      
      - name: Deploy Backend
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/backend-loadbalancer.yaml
          kubectl rollout status deployment/mern-backend --timeout=300s
          echo "Backend deployed successfully"

      - name: Deploy Frontend
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl rollout status deployment/mern-frontend --timeout=300s
          echo "Frontend deployed successfully"
      
      - name: Verify Deployment
        run: |
          echo "Current Pods:"
          kubectl get pods
          echo "Current Services:"
          kubectl get services
          echo "Deployed SHA: $SHA"